### ISSUE TITLE
pdf 中部分符号显示缺失. 

### ISSUE THREAD

**Issue by zzhx2006** [xiaoweiChen/Professional-cpp-6ed#6]
![1](https://github.com/user-attachments/assets/04d1cf34-1f9d-49f0-badd-a12eb9529e44)
在 15.1.5 节的表格中，有一些符号显示的问题. pdf 中有部分符号缺失.

**Comment by zzhx2006** [comment]
看起来，可能把 `operator--` 写成 `operator-{}-` 可以解决？

**Comment by xiaoweiChen** [comment]
感谢勘误~已经修复了
